name: Generate Tags for Adapters

on:
  push:
    branches:
      - 'release/**'

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      rev: ${{ steps.shortrev.outputs.rev }}
      ver: ${{ steps.pversion.outputs.ver }}
      date: ${{ steps.date.outputs.date }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 8
          overwrite-settings: false
      - name: Get short commit hash
        id: shortrev
        run: echo "rev=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get date
        id: date
        run: echo "date=$(date +'%y%m%d' | cut -c 2-)" >> $GITHUB_OUTPUT
      - name: Get project version
        id: pversion
        run: echo "ver=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout| sed -e 's/-SNAPSHOT//g')" >> $GITHUB_OUTPUT

  tag:
    runs-on: ubuntu-latest
    needs: prep
    steps:
      - uses: actions/checkout@v4
      - name: Generate tag name
        id: tagname
        run: echo "tagname=${{ needs.prep.outputs.ver }}-${{ needs.prep.outputs.date }}-${{ needs.prep.outputs.rev }}" >> $GITHUB_OUTPUT

      - name: Fetch tags from remote
        run: git fetch --tags

      - name: Delete existing tags with same version
        run: |
          version="${{ needs.prep.outputs.ver }}"
          for tag in $(git tag -l "${version}-*"); do
            git tag -d "$tag"
            git push origin :refs/tags/$tag
          done

      - name: Create new tag
        run: |
          git tag "${{ steps.tagname.outputs.tagname }}"
          git push origin "${{ steps.tagname.outputs.tagname }}"